language: java

before-install:
  - npm install

cache:
  directories:
  - $HOME/.m2

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
  
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: sk-staging-frontend
    file_glob: true
    file: "frontend/*"
    script: npm start
    on:
      repo: jaflaten/SikkerKommunikasjon
      branch: development
      
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: sk-staging-backend
    file_glob: true
    file: "backend/*"
    on:
      repo: jaflaten/SikkerKommunikasjon
      branch: development

  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: sk-prod-backend
    file_glob: true
    file: "backend/*"
    on:
      repo: jaflaten/SikkerKommunikasjon
      branch: main

  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: sk-prod-frontend
    file_glob: true
    file: "frontend/*"
    script: npm start
    on:
      repo: jaflaten/SikkerKommunikasjon
      branch: main
